# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = "#1d2021"
#background = "#282828"
background = "#171616"
# soft contrast background = = "#32302f"
#foreground = "#ebdbb2"
foreground = "#d5c4a1"

# Normal colors
[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

# Bright colors
[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[cursor.style]
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 13

[font.normal]
family = "MesloLGS NF"

[shell]
program = "/bin/zsh"
