require("main.packer")
require("main.set")
require("main.autocmd")
require("main.configs.ts")
require("main.configs.ale")
require("main.configs.gruvbox")
require("main.configs.lualine")
require("main.configs.indent-blankline")
